myfile = open("text.txt", "w")
myfile.write("This is my first file written with Python. Whoaa!\n")
myfile.write("-------------------------------------------------\n")
myfile.write("Hello, universe!\n")
myfile.close()